name: run cypress tests
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          browser: chrome
          config-file: cypress.config.js
